/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'Tinystormjojo',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arXiv-ai-enhanced',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Get the base URL for raw GitHub content from data branch
     * @returns {string} Base URL for raw GitHub content
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    },

    getGithubRepoUrl: function() {
        return `https://github.com/${this.repoOwner}/${this.repoName}`;
    },

    getGithubRepoApiUrl: function() {
        return `https://api.github.com/repos/${this.repoOwner}/${this.repoName}`;
    },

    /** 将页面上 .github-button、.footer-repo-link 指向当前配置的仓库 */
    syncGithubDomLinks: function() {
        const url = this.getGithubRepoUrl();
        document.querySelectorAll('a.github-button, a.footer-repo-link').forEach((a) => {
            a.href = url;
        });
    }
};

